"Resource/UI/HudPlayerHealth.res"
{
	"PlayerStatusHealthValueBackground"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"PlayerStatusHealthValueBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"3"
		"wide"					"75"
		"wide_minmode"			"0"
		"tall"					"30"
		"tall_minmode"			"0"
		"visible"				"1"
		"enabled"				"1"
		"bgcolor_override"		"TransparentBlack3"
		"pin_to_sibling"		"PlayerStatusHealthValue"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
	}
	"PlayerStatusHealthValueUnderline"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"PlayerStatusHealthValueUnderline"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"4"
		"wide"					"75"
		"wide_minmode"			"0"
		"tall"					"1"
		"tall_minmode"			"0"
		"visible"				"1"
		"enabled"				"1"
		"bgcolor_override"		"HP"
		"paintbackgroundtype"	"0"
		"pin_to_sibling"		"PlayerStatusHealthValueBackground"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
	}
}